languages = {
    "English": {
        "title": "🔐 Advanced Password Generator",
        "length": "🔢 Select password length",
        "digits": "🔢 Include digits",
        "special_char": "🔠 Include special characters",
        "exclude_similar": "🚫 Exclude similar characters (O, 0, l, 1, I)",
        "num_passwords": "🔢 How many passwords to generate?",
        "password": "🔑 Password",
        "strength": "🔍 Strength",
        "generate": "⚡ Generate Password",
        "show_password": "🔓 Show Password",
        "success": "✅ Passwords Generated!",
        "Generate_Random_Password": "📝 Generate a Random Password",
        "num_words": "🔠 Number of words in password",
        "Generate_Random_Password": "🔀 Generate Random Password",
        "expiry_reminder": "🔔 Password expires on",
    },
    "Urdu": {
        "title": "🔐 جدید پاس ورڈ جنریٹر",
        "length": "🔢 پاس ورڈ کی لمبائی منتخب کریں",
        "digits": "🔢 نمبر شامل کریں",
        "special_char": "🔠 خاص کردار شامل کریں",
        "exclude_similar": "🚫 ملتے جلتے حروف خارج کریں (O, 0, l, 1, I)",
        "num_passwords": "🔢 کتنے پاس ورڈز بنانے ہیں؟",
        "password": "🔑 پاس ورڈ",
        "strength": "🔍 مضبوطی",
        "generate": "⚡ پاس ورڈ بنائیں",
        "show_password": "🔓 پاس ورڈ دکھائیں",
        "success": "✅ پاس ورڈز بنائے گئے!",
        "Generate_Random_Password": "📝 بے ترتیب پاس ورڈ بنائیں",
        "num_words": "🔠 پاس ورڈ میں الفاظ کی تعداد",
        "Generate_Random_Password": "🔀 بے ترتیب پاس ورڈ بنائیں",
        "expiry_reminder": "🔔 پاس ورڈ ختم ہونے کی تاریخ",
    },
    "Arabic": {
        "title": "🔐 مولد كلمات المرور المتقدم",
        "length": "🔢 اختر طول كلمة المرور",
        "digits": "🔢 تضمين الأرقام",
        "special_char": "🔠 تضمين الأحرف الخاصة",
        "exclude_similar": "🚫 استبعاد الأحرف المتشابهة (O, 0, l, 1, I)",
        "num_passwords": "🔢 كم عدد كلمات المرور التي تريد إنشاؤها؟",
        "password": "🔑 كلمة المرور",
        "strength": "🔍 القوة",
        "generate": "⚡ إنشاء كلمة المرور",
        "show_password": "🔓 عرض كلمة المرور",
        "success": "✅ تم إنشاء كلمات المرور!",
        "Generate_Random_Password": "📝 إنشاء كلمة مرور عشوائية",
        "num_words": "🔠 عدد الكلمات في كلمة المرور",
        "Generate_Random_Password": "🔀 إنشاء كلمة مرور عشوائية",
        "expiry_reminder": "🔔 كلمة المرور تنتهي في",
    },
    "Chinese": {
        "title": "🔐 高级密码生成器",
        "length": "🔢 选择密码长度",
        "digits": "🔢 包括数字",
        "special_char": "🔠 包括特殊字符",
        "exclude_similar": "🚫 排除相似字符 (O, 0, l, 1, I)",
        "num_passwords": "🔢 生成多少个密码？",
        "password": "🔑 密码",
        "strength": "🔍 强度",
        "generate": "⚡ 生成密码",
        "show_password": "🔓 显示密码",
        "success": "✅ 密码已生成！",
        "Generate_Random_Password": "📝 生成随机密码",
        "num_words": "🔠 密码中的单词数",
        "Generate_Random_Password": "🔀 生成随机密码",
        "expiry_reminder": "🔔 密码到期时间",
    }
}
